version: '3.8'

services:
  # Node.js application service
  microservice:
    build: .
    environment:
      - AUTH_MS_URL=http://host.docker.internal:7999
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8003:8003"
    depends_on:
      db:
        condition: service_healthy

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5