version: "3.8"

services:
  # Node.js application service
  microservice:
    build: .
    environment:
      - NODE_ENV=production
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - TENANT_MS_URL=http://host.docker.internal:8003
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
    ports:
      - "8002:8002"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "fluent-bit-central:24224" # Service name of central Fluent Bit
        tag: "products.service.{{.Name}}.{{.ID}}"      # Custom tag for these logs
        fluentd-async-connect: "true"
        fluentd-retry-wait: "1s"
        fluentd-max-retries: "30"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - products_network
      - shared_logging_network 

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - products_network

  # Redis service
  redis:
    image: redis:alpine
    ports:
      - "6002:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - products_network

networks:
  products_network:
    driver: bridge
  shared_logging_network:
    external: true

volumes:
  redis_data:
  postgres_data:
