apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$3
spec:
  rules:
  - http:
      paths:
      - path: /api/(auth)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /api/(order)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: orders-service
            port:
              number: 80
      - path: /api/(cart)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: orders-service # Assuming orders-service handles /cart/...
            port:
              number: 80
      - path: /api/(product)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: product-service
            port:
              number: 80
      - path: /api/(category)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: product-service # Assuming product-service handles /category/...
            port:
              number: 80
      - path: /api/(tenant)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: tenant-service
            port:
              number: 80
      - path: /api/(wishlist)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: wishlist-service
            port:
              number: 80