apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-gp3
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true" # Jika ingin jadi default
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  # fsType: ext4
  # encrypted: "true"
# allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer # Praktik yang baik