apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  TENANT_ID: 47dd6b24-0b23-46b0-a662-776158d089ba
  ADMIN_TENANT_ID: 47dd6b24-0b23-46b0-a662-776158d089ba
  NODE_EXTRA_CA_CERTS: "./global-bundle.pem"