apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
data:
  JWT_SECRET: YWF3X21hcmtldHBsYWNlX2p3dF9zZWNyZXQ= # base64 of "aaw_marketplace_jwt_secret"
  ADMIN_JWT_SECRET: YWRtaW5fYWF3X21hcmtldHBsYWNlX2p3dF9zZWNyZXQ= # base64 of "admin_aaw_marketplace_jwt_secret"
