apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8004"
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: wishlist
        image: ilhamelhamdi/anak-anak-walid-wishlist-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wishlist-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: wishlist-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wishlist-config
              key: DB_NAME
        - name: DB_SSL
          valueFrom:
            configMapKeyRef:
              name: wishlist-config
              key: DB_SSL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: wishlist-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wishlist-secret
              key: DB_PASSWORD
        - name: TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: TENANT_ID
        - name: ADMIN_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: ADMIN_TENANT_ID
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: JWT_SECRET
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: ADMIN_JWT_SECRET
        - name: LOG_LEVEL_WORKLOAD_TEST
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: LOG_LEVEL_WORKLOAD_TEST
        - name: NODE_EXTRA_CA_CERTS
          value: "/etc/ssl/certs/rds-ca/global-bundle.pem"
        volumeMounts:
        - name: rds-ca-volume
          mountPath: "/etc/ssl/certs/rds-ca"
          readOnly: true
      volumes:
      - name: rds-ca-volume
        configMap:
          name: rds-ca-bundle-configmap
          items:
          - key: global-bundle.pem
            path: global-bundle.pem