
services:
  # Node.js application service
  microservice:
    build: .
    image: ilhamelhamdi/anak-anak-walid-auth-service:latest
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - ADMIN_JWT_SECRET=admin_ms_jwt_secret
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - DB_HOST=db
      - DB_PORT=5432
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224" # Service name of central Fluent Bit
        tag: "auth.service.{{.Name}}.{{.ID}}"      # Custom tag for these logs

    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth_network
      - shared_logging_network 

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth_network

volumes:
  db_data:

networks:
  auth_network:
    driver: bridge
  shared_logging_network:
    external: true
