apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  DB_HOST: order-db.c3ue4uyugmfu.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_SSL: "true"
  REDIS_URL: rediss://order-redis-yvhc6s.serverless.use1.cache.amazonaws.com:6379