apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: orders
        image: ilhamelhamdi/anak-anak-walid-orders-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: DB_NAME
        - name: DB_SSL
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: DB_SSL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: orders-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-secret
              key: DB_PASSWORD
        - name: TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: TENANT_ID
        - name: ADMIN_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: ADMIN_TENANT_ID
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: JWT_SECRET
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: ADMIN_JWT_SECRET
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: REDIS_URL
        - name: PRODUCT_MS_URL # equal to product service
          value: "http://product-service:80"
        - name: NODE_EXTRA_CA_CERTS
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: NODE_EXTRA_CA_CERTS
